# Auto-merge configuration for Dependabot PRs
- match:
    dependency_type: all
    update_type: "semver:minor" # Only merge minor version updates
  conditions:
    - check-success=build
    - check-success=lint
    - check-success=test
  actions:
    merge:
      method: squash