name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.24.3'

    - name: Verify dependencies
      run: go mod verify

    - name: Tidy dependencies
      run: go mod tidy

    - name: Build
      run: |
        echo "Building main package"
        go build -v
        echo "Building all packages"
        go build -v ./...

    - name: Run tests
      run: go test -v ./...