name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.24.3'

    # Apply CI-specific fixes for module issues
    - name: Fix module issues for CI
      run: ./.github/workflows/ci-fix.sh

    # Simplest possible CI workflow for now
    - name: Build app
      run: go build