name: golangci-lint
on:
  push:
    branches:
      - main
  pull_request:

permissions:
  contents: read

jobs:
  golangci:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-go@v5
        with:
          go-version: '1.21'
          cache: true

      - name: Setup custom GOPATH for project
        run: |
          mkdir -p $HOME/go/src/mcpterm-go
          cp -r $GITHUB_WORKSPACE/* $HOME/go/src/mcpterm-go/
          cd $HOME/go/src/mcpterm-go
          go mod tidy

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: latest
          args: --timeout=5m
          working-directory: ${{ env.GOPATH }}/src/mcpterm-go
        env:
          GOPATH: ${{ runner.home }}/go