name: Lint

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  golangci:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.24.3'

      - name: Initialize Go modules
        run: |
          go mod tidy
          go mod download

      - name: Build code
        run: go build -v ./...

      - name: Install golangci-lint
        run: go install github.com/golangci/golangci-lint/cmd/golangci-lint@v1.56.1

      - name: Run golangci-lint
        run: |
          golangci-lint run --config=.golangci.yml --timeout=5m