name: Lint

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  lint:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.24.3'

      # Apply CI-specific fixes for module issues
      - name: Fix module issues for CI
        run: ./.github/workflows/ci-fix.sh

      # Simple vet check
      - name: Run go vet
        run: go vet