name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  goreleaser:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.21'
          check-latest: true

      - name: Setup custom GOPATH for project
        run: |
          mkdir -p $HOME/go/src/mcpterm-go
          cp -r $GITHUB_WORKSPACE/* $HOME/go/src/mcpterm-go/
          cd $HOME/go/src/mcpterm-go
          go mod tidy

      - name: Test
        working-directory: ${{ env.GOPATH }}/src/mcpterm-go
        run: go test -v ./...
        env:
          GOPATH: ${{ runner.home }}/go

      - name: Build binaries
        working-directory: ${{ env.GOPATH }}/src/mcpterm-go
        run: |
          GOOS=linux GOARCH=amd64 go build -v -o $GITHUB_WORKSPACE/mcpterm-linux-amd64
          GOOS=darwin GOARCH=amd64 go build -v -o $GITHUB_WORKSPACE/mcpterm-darwin-amd64
          GOOS=darwin GOARCH=arm64 go build -v -o $GITHUB_WORKSPACE/mcpterm-darwin-arm64
          GOOS=windows GOARCH=amd64 go build -v -o $GITHUB_WORKSPACE/mcpterm-windows-amd64.exe
        env:
          GOPATH: ${{ runner.home }}/go

      - name: Create Release
        id: create_release
        uses: softprops/action-gh-release@v2
        with:
          name: Release ${{ github.ref_name }}
          draft: false
          prerelease: false
          files: |
            mcpterm-linux-amd64
            mcpterm-darwin-amd64
            mcpterm-darwin-arm64
            mcpterm-windows-amd64.exe